export const demoFocusDate = new Date(2026, 4, 5);
export const demoProjects = [
  {
    id: 'demo-project-karun-phuket',
    name: 'Karun Phuket',
    phase: 'Design',
    status: 'In Progress',
    startDate: '2026-05-04',
    endDate: '2026-05-20',
    notes: 'Design direction, client alignment, and phase approvals.',
  },
  {
    id: 'demo-project-karun-central-westville',
    name: 'Karun Central Westville',
    phase: 'Construction',
    status: 'Overdue',
    startDate: '2026-05-04',
    endDate: '2026-05-07',
    notes: 'Construction coordination and BOQ updates.',
  },
  {
    id: 'demo-project-ultimate-bkk',
    name: 'Ultimate BKK',
    phase: 'Handover',
    status: 'Planned',
    startDate: '2026-05-15',
    endDate: '2026-05-20',
    notes: 'Handover planning and final documentation.',
  },
  {
    id: 'demo-project-avery-wong',
    name: 'Avery Wong',
    phase: 'Design',
    status: 'In Progress',
    startDate: '2026-05-05',
    endDate: '2026-05-12',
    notes: 'Design sprint and client direction.',
  },
  {
    id: 'demo-project-yum-nine',
    name: 'YUM NINE',
    phase: 'Design',
    status: 'Planned',
    startDate: '2026-05-06',
    endDate: '2026-05-16',
    notes: 'Brand and spatial planning.',
  },
  {
    id: 'demo-project-stayr-layr',
    name: 'STAYR LAYR',
    phase: 'Construction',
    status: 'In Progress',
    startDate: '2026-05-07',
    endDate: '2026-05-14',
    notes: 'Construction coordination.',
  },
  {
    id: 'demo-project-football-brief',
    name: 'The Football Brief',
    phase: 'Opening',
    status: 'Planned',
    startDate: '2026-05-08',
    endDate: '2026-05-09',
    notes: 'Opening plan and launch checklist.',
  },
  {
    id: 'demo-project-karun-boq',
    name: 'Karun BOQ',
    phase: 'Construction',
    status: 'Overdue',
    startDate: '2026-05-10',
    endDate: '2026-05-13',
    notes: 'BOQ review needs attention.',
  },
  {
    id: 'demo-project-site-survey',
    name: 'Site Survey',
    phase: 'Handover',
    status: 'Done',
    startDate: '2026-05-11',
    endDate: '2026-05-11',
    notes: 'Survey completed.',
  },
  {
    id: 'demo-project-client-review',
    name: 'Client Review',
    phase: 'Design',
    status: 'Planned',
    startDate: '2026-05-12',
    endDate: '2026-05-18',
    notes: 'Client review window.',
  },
  {
    id: 'demo-project-studio-ops-review',
    name: 'Studio Ops Review',
    phase: 'Opening',
    status: 'Planned',
    startDate: '2026-05-05',
    endDate: '2026-05-10',
    notes: 'Internal operations review for stress testing range stacking.',
  },
];
export const demoTasks = [
  {
    id: 'demo-range-karun-phuket',
    title: 'Karun Phuket',
    detail: 'Design phase',
    notes: 'Karun Phuket design phase timeline.',
    projectId: 'demo-project-karun-phuket',
    projectName: 'Karun Phuket',
    project: 'Karun Phuket',
    phase: 'Design',
    startDate: '2026-05-04',
    endDate: '2026-05-20',
    status: 'todo',
    type: 'phase',
  },
  {
    id: 'demo-range-karun-central-westville',
    title: 'Karun Central Westville',
    detail: 'Construction phase',
    notes: 'Karun Central Westville construction phase timeline.',
    projectId: 'demo-project-karun-central-westville',
    projectName: 'Karun Central Westville',
    project: 'Karun Central Westville',
    phase: 'Construction',
    startDate: '2026-05-04',
    endDate: '2026-05-07',
    status: 'overdue',
    type: 'phase',
  },
  {
    id: 'demo-range-ultimate-bkk',
    title: 'Ultimate BKK',
    detail: 'Handover phase',
    notes: 'Ultimate BKK handover phase timeline.',
    projectId: 'demo-project-ultimate-bkk',
    projectName: 'Ultimate BKK',
    project: 'Ultimate BKK',
    phase: 'Handover',
    startDate: '2026-05-15',
    endDate: '2026-05-20',
    status: 'planned',
    type: 'phase',
  },
  {
    id: 'demo-range-avery-wong',
    title: 'Avery Wong',
    detail: 'Design phase',
    notes: 'Avery Wong design timeline.',
    projectId: 'demo-project-avery-wong',
    projectName: 'Avery Wong',
    project: 'Avery Wong',
    phase: 'Design',
    startDate: '2026-05-05',
    endDate: '2026-05-12',
    status: 'in progress',
    type: 'phase',
  },
  {
    id: 'demo-range-yum-nine',
    title: 'YUM NINE',
    detail: 'Design phase',
    notes: 'YUM NINE planning timeline.',
    projectId: 'demo-project-yum-nine',
    projectName: 'YUM NINE',
    project: 'YUM NINE',
    phase: 'Design',
    startDate: '2026-05-06',
    endDate: '2026-05-16',
    status: 'planned',
    type: 'phase',
  },
  {
    id: 'demo-range-stayr-layr',
    title: 'STAYR LAYR',
    detail: 'Construction phase',
    notes: 'STAYR LAYR construction timeline.',
    projectId: 'demo-project-stayr-layr',
    projectName: 'STAYR LAYR',
    project: 'STAYR LAYR',
    phase: 'Construction',
    startDate: '2026-05-07',
    endDate: '2026-05-14',
    status: 'in progress',
    type: 'phase',
  },
  {
    id: 'demo-range-football-brief',
    title: 'The Football Brief',
    detail: 'Opening phase',
    notes: 'The Football Brief opening window.',
    projectId: 'demo-project-football-brief',
    projectName: 'The Football Brief',
    project: 'The Football Brief',
    phase: 'Opening',
    startDate: '2026-05-08',
    endDate: '2026-05-09',
    status: 'planned',
    type: 'phase',
  },
  {
    id: 'demo-range-karun-boq',
    title: 'Karun BOQ',
    detail: 'Construction phase',
    notes: 'Karun BOQ overdue range.',
    projectId: 'demo-project-karun-boq',
    projectName: 'Karun BOQ',
    project: 'Karun BOQ',
    phase: 'Construction',
    startDate: '2026-05-10',
    endDate: '2026-05-13',
    status: 'overdue',
    type: 'phase',
  },
  {
    id: 'demo-range-site-survey',
    title: 'Site Survey',
    detail: 'Handover phase',
    notes: 'Site Survey completed.',
    projectId: 'demo-project-site-survey',
    projectName: 'Site Survey',
    project: 'Site Survey',
    phase: 'Handover',
    startDate: '2026-05-11',
    endDate: '2026-05-11',
    status: 'done',
    type: 'phase',
  },
  {
    id: 'demo-range-client-review',
    title: 'Client Review',
    detail: 'Design phase',
    notes: 'Client Review design window.',
    projectId: 'demo-project-client-review',
    projectName: 'Client Review',
    project: 'Client Review',
    phase: 'Design',
    startDate: '2026-05-12',
    endDate: '2026-05-18',
    status: 'planned',
    type: 'phase',
  },
  {
    id: 'demo-range-studio-ops-review',
    title: 'Studio Ops Review',
    detail: 'Opening phase',
    notes: 'Internal operations review for stress testing range stacking.',
    projectId: 'demo-project-studio-ops-review',
    projectName: 'Studio Ops Review',
    project: 'Studio Ops Review',
    phase: 'Opening',
    startDate: '2026-05-05',
    endDate: '2026-05-10',
    status: 'planned',
    type: 'phase',
  },
  {
    id: 'demo-task-site-meeting',
    title: 'Site meeting with client',
    detail: 'Client walkthrough and design alignment.',
    notes: 'Client walkthrough and design alignment.',
    projectId: 'demo-project-karun-phuket',
    projectName: 'Karun Phuket',
    project: 'Karun Phuket',
    phase: 'Design',
    date: '2026-05-05',
    dueDate: '2026-05-05',
    startDate: '2026-05-05',
    endDate: '2026-05-05',
    startTime: '09:00',
    endTime: '10:30',
    status: 'todo',
  },
  {
    id: 'demo-task-moodboard-review',
    title: 'Moodboard review',
    detail: 'Review visual direction and references.',
    notes: 'Review visual direction and references.',
    projectId: 'demo-project-karun-phuket',
    projectName: 'Karun Phuket',
    project: 'Karun Phuket',
    phase: 'Design',
    date: '2026-05-05',
    dueDate: '2026-05-05',
    startDate: '2026-05-05',
    endDate: '2026-05-05',
    startTime: '14:00',
    endTime: '15:00',
    status: 'todo',
  },
  {
    id: 'demo-task-update-boq',
    title: 'Update BOQ',
    detail: 'Revise construction cost items.',
    notes: 'Revise construction cost items.',
    projectId: 'demo-project-karun-central-westville',
    projectName: 'Karun Central Westville',
    project: 'Karun Central Westville',
    phase: 'Construction',
    date: '2026-05-05',
    dueDate: '2026-05-05',
    startDate: '2026-05-05',
    endDate: '2026-05-05',
    startTime: '18:00',
    endTime: '19:00',
    status: 'todo',
  },
  {
    id: 'demo-task-material-samples',
    title: 'Material samples',
    detail: 'Confirm stone and wood samples.',
    notes: 'Confirm stone and wood samples.',
    projectId: 'demo-project-avery-wong',
    projectName: 'Avery Wong',
    project: 'Avery Wong',
    phase: 'Design',
    date: '2026-05-05',
    dueDate: '2026-05-05',
    startDate: '2026-05-05',
    endDate: '2026-05-05',
    startTime: '11:00',
    endTime: '11:30',
    status: 'todo',
  },
  {
    id: 'demo-task-vendor-call',
    title: 'Vendor call',
    detail: 'Align lead times and approvals.',
    notes: 'Align lead times and approvals.',
    projectId: 'demo-project-yum-nine',
    projectName: 'YUM NINE',
    project: 'YUM NINE',
    phase: 'Design',
    date: '2026-05-05',
    dueDate: '2026-05-05',
    startDate: '2026-05-05',
    endDate: '2026-05-05',
    startTime: '16:00',
    endTime: '16:30',
    status: 'todo',
  },
  {
    id: 'demo-task-review-construction-drawing',
    title: 'Review construction drawing',
    detail: 'Check updated drawing package.',
    notes: 'Check updated drawing package.',
    projectId: 'demo-project-karun-phuket',
    projectName: 'Karun Phuket',
    project: 'Karun Phuket',
    phase: 'Design',
    date: '2026-05-12',
    dueDate: '2026-05-12',
    startDate: '2026-05-12',
    endDate: '2026-05-12',
    status: 'later',
  },
  {
    id: 'demo-task-budget-approval',
    title: 'Budget approval',
    detail: 'Prepare approval pack.',
    notes: 'Prepare approval pack.',
    projectId: 'demo-project-ultimate-bkk',
    projectName: 'Ultimate BKK',
    project: 'Ultimate BKK',
    phase: 'Handover',
    date: '2026-05-15',
    dueDate: '2026-05-15',
    startDate: '2026-05-15',
    endDate: '2026-05-15',
    status: 'later',
  },
  {
    id: 'demo-task-site-survey',
    title: 'Site survey',
    detail: 'Completed initial site survey.',
    notes: 'Completed initial site survey.',
    projectId: 'demo-project-karun-phuket',
    projectName: 'Karun Phuket',
    project: 'Karun Phuket',
    phase: 'Design',
    date: '2026-05-01',
    dueDate: '2026-05-01',
    startDate: '2026-05-01',
    endDate: '2026-05-01',
    status: 'done',
  },
];
export const demoNotes = [
  {
    id: 'demo-note-karun-phuket',
    projectId: 'demo-project-karun-phuket',
    projectName: 'Karun Phuket',
    body: 'Design review focuses on guest journey, material mood, and approval-ready boards.',
  },
  {
    id: 'demo-note-karun-central-westville',
    projectId: 'demo-project-karun-central-westville',
    projectName: 'Karun Central Westville',
    body: 'Construction sprint is focused on BOQ updates and site coordination.',
  },
  {
    id: 'demo-note-ultimate-bkk',
    projectId: 'demo-project-ultimate-bkk',
    projectName: 'Ultimate BKK',
    body: 'Handover planning starts with budget approval and documentation cleanup.',
  },
];
