import { AtmosphereRecipe, VisualDirectionAnalysis } from '../types';

export function createAtmosphereRecipe(analysis?: VisualDirectionAnalysis): AtmosphereRecipe {
  const now = new Date().toISOString(); const text = `${analysis?.timeOfDayWeather || ''} ${analysis?.lightingDirection || ''}`.toLowerCase();
  const timeOfDay = /sunset/.test(text) ? 'sunset' : /night|evening/.test(text) ? 'night' : /late afternoon/.test(text) ? 'late_afternoon' : /morning/.test(text) ? 'morning' : /midday|daylight/.test(text) ? 'midday' : 'mixed_custom';
  return { id: crypto.randomUUID(), version: 1, timeOfDay, sunCharacter: 'Use only confirmed scene/reference evidence.', sunDirectionDescription: 'Uncertain unless explicitly supplied; do not infer a precise direction from one image.', shadowLength: 'Natural for time of day', shadowSoftness: 'Soft to realistic', skyCondition: 'custom', weather: 'Preserve existing conditions unless scoped direction says otherwise.', daylightStrength: 'Balanced', artificialLightingState: 'Preserve existing fixture logic', interiorExteriorBalance: 'Plausible', whiteBalance: 'neutral', exposure: 'Balanced editorial exposure', contrast: 'Natural', saturation: 'Restrained', bloom: 'Minimal', haze: 'None unless referenced', reflectionCharacter: 'Physically plausible', imageClarity: 'Clean architectural photography', emotionalTone: analysis?.overallAtmosphere || 'Natural architectural realism', photographyCharacter: analysis?.photographicTreatment || 'Architectural editorial photography', sourceReferenceIds: analysis?.referenceUsageMap.map((item) => item.referenceId) || [], userNotes: '', confidence: analysis?.analysisSource === 'vision' ? 75 : 50, analysisMode: analysis?.analysisSource || 'not_analyzed', createdAt: now, updatedAt: now };
}

export function atmospherePromptLines(recipe: AtmosphereRecipe) { return [`Atmosphere recipe: ${recipe.timeOfDay.replace(/_/g, ' ')}, ${recipe.emotionalTone}.`, `Lighting: ${recipe.daylightStrength}; ${recipe.shadowSoftness} shadows; ${recipe.whiteBalance.replace(/_/g, ' ')} white balance.`, `Photography: ${recipe.photographyCharacter}; ${recipe.contrast} contrast; ${recipe.reflectionCharacter} reflections.`]; }
