import { CameraContract, MaterialZone, SceneContract, SpaceType } from '../types';
import { spaceTypeLabel } from './spaceTypes';

const now = () => new Date().toISOString();
const commonLocked = ['Camera viewpoint, crop, aspect ratio, verticals, and perspective', 'Architecture and geometry', 'Walls, floors, ceilings, openings, and built-ins', 'Fixtures, equipment, furniture placement, and circulation paths', 'Material zoning and visible signage/branding'];
const commonFlexible = ['Exposure and light intensity', 'Texture realism and reflection quality', 'Minor props and soft styling', 'People/activity when requested', 'Subtle color grading and weather'];

const baselineBySpace: Record<SpaceType, { locked: string[]; flexible: string[]; forbidden: string[]; zones: Array<Pick<MaterialZone, 'label' | 'type'>> }> = {
  kitchen: { locked: ['Cabinet modules, panel divisions, appliance type/location, sink, hob, hood, oven, refrigerator, tall-unit locations', 'Countertop and backsplash zoning', 'Believable working clearances'], flexible: ['Material realism within existing cabinetry/countertop zones'], forbidden: ['Do not invent handles or alter door-opening logic.', 'Do not move plumbing or cooking equipment.'], zones: [{ label: 'Cabinetry', type: 'cabinetry' }, { label: 'Countertop', type: 'countertop' }, { label: 'Backsplash', type: 'backsplash' }, { label: 'Floor', type: 'floor' }] },
  bathroom: { locked: ['Fixture locations, wet/dry zoning, visible floor-drain and shower-enclosure logic', 'Sanitaryware type and waterproof material zoning'], flexible: ['Surface realism within existing wet-area zones'], forbidden: ['Do not alter sanitaryware type or fixture locations.', 'Maintain plausible waterproof material use.'], zones: [{ label: 'Floor', type: 'floor' }, { label: 'Wall', type: 'wall' }, { label: 'Glass / Shower', type: 'glass_glazing' }] },
  living_room: { locked: ['Furniture identity and placement, circulation paths, built-ins, TV wall, openings, and ceiling'], flexible: ['Light styling additions and textile realism'], forbidden: ['Styling additions must not obstruct focal architecture or circulation.'], zones: [{ label: 'Floor', type: 'floor' }, { label: 'Wall', type: 'wall' }, { label: 'Upholstery', type: 'upholstery' }, { label: 'Loose Furniture', type: 'loose_furniture' }] },
  bedroom: { locked: ['Bed location/orientation, wardrobe, openings, circulation, and built-in dimensions'], flexible: ['Light styling, textile and surface realism'], forbidden: ['Do not change mattress size or built-in dimensions.', 'Styling additions remain light by default.'], zones: [{ label: 'Floor', type: 'floor' }, { label: 'Wall', type: 'wall' }, { label: 'Upholstery', type: 'upholstery' }, { label: 'Curtain / Fabric', type: 'curtain_fabric' }] },
  residential_exterior: { locked: ['Building massing, openings, roof, facade modules, driveway, access, and property boundaries'], flexible: ['Landscape density only within allowed areas', 'Weather and photographic realism'], forbidden: ['Do not invent floors, balconies, canopies, or facade openings.', 'Landscape must not obstruct entrances, parking, glazing, or circulation.'], zones: [{ label: 'Facade', type: 'wall' }, { label: 'Glass / Glazing', type: 'glass_glazing' }, { label: 'Exterior Ground / Driveway', type: 'exterior_ground_driveway' }, { label: 'Landscape', type: 'landscape' }] },
  garden_landscape: { locked: ['Hardscape, driveway, steps, boundaries, pool, and building access'], flexible: ['Vegetation within defined flexibility and plausible maintenance'], forbidden: ['Vegetation must not invade buildings, access zones, or circulation.'], zones: [{ label: 'Landscape', type: 'landscape' }, { label: 'Water', type: 'water' }, { label: 'Exterior Ground / Driveway', type: 'exterior_ground_driveway' }] },
  garage_carport: { locked: ['Parking capacity, vehicle circulation, gates, columns, storage, and service access'], flexible: ['Light/material realism only'], forbidden: ['Do not place plants or furniture in parking clearance.'], zones: [{ label: 'Exterior Ground / Driveway', type: 'exterior_ground_driveway' }, { label: 'Metal', type: 'metal' }] },
  dining_room: { locked: ['Dining furniture identity/placement, openings, circulation, and built-ins'], flexible: ['Table styling and lighting response'], forbidden: ['Do not obstruct circulation.'], zones: [{ label: 'Floor', type: 'floor' }, { label: 'Loose Furniture', type: 'loose_furniture' }] },
  home_office: { locked: ['Desk, storage, equipment, openings, and circulation'], flexible: ['Surface realism and light styling'], forbidden: ['Do not move equipment or block working clearances.'], zones: [{ label: 'Floor', type: 'floor' }, { label: 'Cabinetry', type: 'cabinetry' }] },
  walk_in_closet: { locked: ['Wardrobe modules, hanging/storage zones, openings, and circulation'], flexible: ['Finish realism and limited styling'], forbidden: ['Do not alter storage logic or cabinet divisions.'], zones: [{ label: 'Cabinetry', type: 'cabinetry' }, { label: 'Floor', type: 'floor' }] },
  pool_terrace: { locked: ['Pool, terrace, hardscape, boundaries, building access, and safety edges'], flexible: ['Weather, water realism, and allowed planting'], forbidden: ['Do not obstruct access or invent structural elements.'], zones: [{ label: 'Water', type: 'water' }, { label: 'Landscape', type: 'landscape' }, { label: 'Exterior Ground / Driveway', type: 'exterior_ground_driveway' }] },
  courtyard: { locked: ['Openings, hardscape, boundaries, access, and architectural massing'], flexible: ['Planting and atmosphere within allowed zones'], forbidden: ['Do not change courtyard geometry or block entries.'], zones: [{ label: 'Landscape', type: 'landscape' }, { label: 'Exterior Ground / Driveway', type: 'exterior_ground_driveway' }] },
  facade_detail: { locked: ['Facade modules, glazing, joints, openings, and material boundaries'], flexible: ['Material texture and reflections'], forbidden: ['Do not invent facade openings or alter modules.'], zones: [{ label: 'Wall', type: 'wall' }, { label: 'Glass / Glazing', type: 'glass_glazing' }, { label: 'Metal', type: 'metal' }] },
  multi_purpose_room: { locked: ['Architecture, openings, built-ins, furniture placement, and circulation'], flexible: ['Lighting and limited styling'], forbidden: ['Do not obstruct circulation or change built-ins.'], zones: [{ label: 'Floor', type: 'floor' }, { label: 'Wall', type: 'wall' }, { label: 'Loose Furniture', type: 'loose_furniture' }] },
  other: { locked: [], flexible: [], forbidden: ['Do not redesign the Base Render or invent architectural elements.'], zones: [{ label: 'Floor', type: 'floor' }, { label: 'Wall', type: 'wall' }, { label: 'Ceiling', type: 'ceiling' }] },
};

export function defaultCameraContract(): CameraContract { return { lockMode: 'strict', preserveViewpoint: true, preserveCrop: true, preserveAspectRatio: true, preservePerspectiveCharacter: true, preserveHorizon: true, preserveVerticalCorrection: true, preserveLensCharacter: true, cameraMovementAllowance: 'No camera movement.', cropTolerance: 'No crop change.', notes: 'Do not claim focal length unless supplied by the user.' }; }

export function createSceneContract(projectId: string, sceneId: string, spaceType: SpaceType = 'other'): SceneContract {
  const baseline = baselineBySpace[spaceType]; const createdAt = now();
  return { id: crypto.randomUUID(), projectId, sceneId, version: 1, spaceType, lockedElements: [...commonLocked, ...baseline.locked], flexibleElements: [...commonFlexible, ...baseline.flexible], explicitlyEditableElements: [], forbiddenChanges: [...baseline.forbidden], materialZones: baseline.zones.map((zone) => ({ id: crypto.randomUUID(), ...zone, currentMaterialDescription: '', flexibility: 'locked', allowedChanges: ['Improve texture realism, finish response, and controlled reflections only.'], forbiddenChanges: ['Do not relocate this material zone or copy reference form/layout.'], linkedReferenceIds: [], userNotes: '' })), cameraContract: defaultCameraContract(), consistencyContract: [`Keep ${spaceTypeLabel(spaceType)} design logic consistent across this scene set.`], source: 'default_baseline', createdAt, updatedAt: createdAt };
}

export function baselinePromptLines(contract: SceneContract) { return [...contract.lockedElements.map((item) => `Lock: ${item}`), ...contract.forbiddenChanges.map((item) => `Forbidden: ${item}`), ...contract.materialZones.filter((zone) => zone.flexibility !== 'editable').map((zone) => `Material zone ${zone.label} remains ${zone.flexibility}; ${zone.forbiddenChanges.join(' ')}`)]; }
